channels:
  - anaconda
  - bokeh
  - defaults
dependencies:
  - blas=1.0=mkl
  - bokeh=3.1.0=py_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - pandas
  - numpy
  - scipy
  - pip
  - seaborn
  - shapely
  - pip:
    - nbserverproxy
    - jupyter-server-proxy
